num1 = input('enter first number : ')
num2 = input('enter second number : ')
num3 = input('enter third number : ')
num1=int(num1)
num2=int(num2)
num3=int(num3)
total1=(num1+num2)
result=(total1*num3)
print('the answer is',result)
